Content-Type: multipart/mixed; boundary="===============0029737330039126096=="
MIME-Version: 1.0
Subject: Simple message
From: sender@sending.domain
To: rcpt@receiver.domain

--===============0029737330039126096==
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

VGhpcyBpcyBhIHNpbXBsZSBtZXNzYWdlLgpBbmQgYSB2ZXJ5IHNpbXBsZSBvbmUuIArmiJHmmK/k
uK3mloflrZcg5ouJ5ouJ5ouJ

--===============0029737330039126096==
Content-Type: application/octet-stream
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="test.text"


--===============0029737330039126096==--
